#!/usr/bin/env bash

# dislay "Best School" 10 times using a while loop.

# on the 9th iteration, display "Hi" before "Best School".

cnt=0

while [ $cnt -lt 10 ]
do 
	if[ $cnt -eq 9]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( cnt++ ))
done
